# Build statistics from .ninja_log (no Python required)
# Usage: cmake -P BuildStats.cmake (run from build directory)

set(NINJA_LOG ".ninja_log")
if(NOT EXISTS "${NINJA_LOG}")
    message(FATAL_ERROR "No .ninja_log found. Run build first.")
endif()

# Read and parse ninja log
file(STRINGS "${NINJA_LOG}" LINES)

# Module accumulators + wall clock tracking
set(MODULES "")
set(MIN_START 999999999999)
set(MAX_END 0)
foreach(LINE ${LINES})
    if(LINE MATCHES "^#")
        continue()
    endif()

    # Format: start \t end \t mtime \t output \t hash
    string(REPLACE "\t" ";" PARTS "${LINE}")
    list(LENGTH PARTS LEN)
    if(LEN LESS 4)
        continue()
    endif()

    list(GET PARTS 0 START)
    list(GET PARTS 1 END)
    list(GET PARTS 3 OBJ_FILE)
    math(EXPR DURATION "${END} - ${START}")

    # Track wall clock bounds
    if(START LESS MIN_START)
        set(MIN_START ${START})
    endif()
    if(END GREATER MAX_END)
        set(MAX_END ${END})
    endif()

    # Determine module from path (more granular)
    if(OBJ_FILE MATCHES "external/nvImageCodec")
        set(MODULE "nvImageCodec")
    elseif(OBJ_FILE MATCHES "external/imguizmo")
        set(MODULE "imguizmo")
    # training_new submodules
    elseif(OBJ_FILE MATCHES "src/training_new/rasterization")
        set(MODULE "training/rasterizer")
    elseif(OBJ_FILE MATCHES "src/training_new/kernels")
        set(MODULE "training/kernels")
    elseif(OBJ_FILE MATCHES "src/training_new")
        set(MODULE "training/other")
    # core_new submodules
    elseif(OBJ_FILE MATCHES "src/core_new/tensor")
        set(MODULE "core/tensor")
    elseif(OBJ_FILE MATCHES "src/core_new/cuda")
        set(MODULE "core/cuda")
    elseif(OBJ_FILE MATCHES "src/core_new")
        set(MODULE "core/other")
    # rendering_new submodules
    elseif(OBJ_FILE MATCHES "src/rendering_new/rasterizer")
        set(MODULE "rendering/rasterizer")
    elseif(OBJ_FILE MATCHES "src/rendering_new.*\\.cu")
        set(MODULE "rendering/cuda")
    elseif(OBJ_FILE MATCHES "src/rendering_new")
        set(MODULE "rendering/other")
    elseif(OBJ_FILE MATCHES "src/visualizer_new")
        set(MODULE "visualizer")
    elseif(OBJ_FILE MATCHES "src/loader_new")
        set(MODULE "loader")
    elseif(OBJ_FILE MATCHES "src/geometry_new")
        set(MODULE "geometry")
    elseif(OBJ_FILE MATCHES "src/project_new")
        set(MODULE "project")
    else()
        set(MODULE "other")
    endif()

    # Accumulate
    if(NOT MODULE IN_LIST MODULES)
        list(APPEND MODULES ${MODULE})
        set(TIME_${MODULE} 0)
        set(FILES_${MODULE} 0)
    endif()
    math(EXPR TIME_${MODULE} "${TIME_${MODULE}} + ${DURATION}")
    math(EXPR FILES_${MODULE} "${FILES_${MODULE}} + 1")
endforeach()

# Calculate total
set(TOTAL_TIME 0)
set(TOTAL_FILES 0)
foreach(MOD ${MODULES})
    math(EXPR TOTAL_TIME "${TOTAL_TIME} + ${TIME_${MOD}}")
    math(EXPR TOTAL_FILES "${TOTAL_FILES} + ${FILES_${MOD}}")
endforeach()

# Sort by time (selection sort)
set(SORTED_MODULES "")
while(MODULES)
    set(MAX_TIME -1)
    set(MAX_MOD "")
    foreach(MOD ${MODULES})
        if(TIME_${MOD} GREATER MAX_TIME)
            set(MAX_TIME ${TIME_${MOD}})
            set(MAX_MOD ${MOD})
        endif()
    endforeach()
    list(APPEND SORTED_MODULES ${MAX_MOD})
    list(REMOVE_ITEM MODULES ${MAX_MOD})
endwhile()
set(MODULES ${SORTED_MODULES})

# Print header
message("")
message("┌────────────────────────┬──────────┬───────┬───────┐")
message("│ Module                 │     Time │ Files │     % │")
message("├────────────────────────┼──────────┼───────┼───────┤")

# Print each module
foreach(MOD ${MODULES})
    math(EXPR SECS "${TIME_${MOD}} / 1000")
    math(EXPR TENTHS "(${TIME_${MOD}} % 1000) / 100")
    if(TOTAL_TIME GREATER 0)
        math(EXPR PCT "(${TIME_${MOD}} * 100) / ${TOTAL_TIME}")
    else()
        set(PCT 0)
    endif()

    # Pad module name to 22 chars
    set(MOD_PADDED "${MOD}")
    string(LENGTH "${MOD_PADDED}" MOD_LEN)
    while(MOD_LEN LESS 22)
        string(APPEND MOD_PADDED " ")
        string(LENGTH "${MOD_PADDED}" MOD_LEN)
    endwhile()

    # Pad seconds (right-align in 5 chars)
    set(SECS_STR "${SECS}")
    string(LENGTH "${SECS_STR}" SECS_LEN)
    while(SECS_LEN LESS 5)
        set(SECS_STR " ${SECS_STR}")
        string(LENGTH "${SECS_STR}" SECS_LEN)
    endwhile()

    # Pad files (right-align in 5 chars)
    set(FILES_STR "${FILES_${MOD}}")
    string(LENGTH "${FILES_STR}" FILES_LEN)
    while(FILES_LEN LESS 5)
        set(FILES_STR " ${FILES_STR}")
        string(LENGTH "${FILES_STR}" FILES_LEN)
    endwhile()

    # Pad percent (right-align in 4 chars)
    set(PCT_STR "${PCT}")
    string(LENGTH "${PCT_STR}" PCT_LEN)
    while(PCT_LEN LESS 4)
        set(PCT_STR " ${PCT_STR}")
        string(LENGTH "${PCT_STR}" PCT_LEN)
    endwhile()

    message("│ ${MOD_PADDED} │ ${SECS_STR}.${TENTHS}s │ ${FILES_STR} │ ${PCT_STR}% │")
endforeach()

# Print total
message("├────────────────────────┼──────────┼───────┼───────┤")
math(EXPR TOTAL_SECS "${TOTAL_TIME} / 1000")
math(EXPR TOTAL_TENTHS "(${TOTAL_TIME} % 1000) / 100")

# Pad seconds (right-align in 5 chars)
set(SECS_STR "${TOTAL_SECS}")
string(LENGTH "${SECS_STR}" SECS_LEN)
while(SECS_LEN LESS 5)
    set(SECS_STR " ${SECS_STR}")
    string(LENGTH "${SECS_STR}" SECS_LEN)
endwhile()

# Pad files (right-align in 5 chars)
set(FILES_STR "${TOTAL_FILES}")
string(LENGTH "${FILES_STR}" FILES_LEN)
while(FILES_LEN LESS 5)
    set(FILES_STR " ${FILES_STR}")
    string(LENGTH "${FILES_STR}" FILES_LEN)
endwhile()

message("│ TOTAL                  │ ${SECS_STR}.${TOTAL_TENTHS}s │ ${FILES_STR} │  100% │")
message("└────────────────────────┴──────────┴───────┴───────┘")

# Calculate wall clock time and parallelism
math(EXPR WALL_TIME "${MAX_END} - ${MIN_START}")
if(WALL_TIME GREATER 0)
    math(EXPR WALL_SECS "${WALL_TIME} / 1000")
    math(EXPR WALL_TENTHS "(${WALL_TIME} % 1000) / 100")
    math(EXPR PARALLELISM "(${TOTAL_TIME} * 10) / ${WALL_TIME}")
    math(EXPR PAR_WHOLE "${PARALLELISM} / 10")
    math(EXPR PAR_FRAC "${PARALLELISM} % 10")

    # Get CPU core count
    include(ProcessorCount)
    ProcessorCount(NPROC)
    if(NPROC EQUAL 0)
        set(NPROC "?")
        set(EFFICIENCY "")
    else()
        math(EXPR EFF_PCT "(${PARALLELISM} * 100) / (${NPROC} * 10)")
        set(EFFICIENCY " (${EFF_PCT}%)")
    endif()

    message("")
    message("Wall time: ${WALL_SECS}.${WALL_TENTHS}s | Cores: ${NPROC} | Parallelism: ${PAR_WHOLE}.${PAR_FRAC}x${EFFICIENCY}")
endif()
