# SPDX-FileCopyrightText: 2025 LichtFeld Studio Authors
# SPDX-License-Identifier: GPL-3.0-or-later
cmake_policy(PUSH)
cmake_policy(SET CMP0057 NEW)
foreach(required MANIFEST COLMAP_ROOT SUPERRES_ROOT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
file(READ "${MANIFEST}" payload)
if(NOT DEFINED NOTICES_ROOT)
    get_filename_component(_manifest_directory "${MANIFEST}" DIRECTORY)
    set(NOTICES_ROOT "${_manifest_directory}/licenses")
endif()
if(NOT EXISTS "${NOTICES_ROOT}/THIRD_PARTY_NOTICES.md")
    message(FATAL_ERROR "Missing runtime provenance/notices status record")
endif()
file(SIZE "${NOTICES_ROOT}/THIRD_PARTY_NOTICES.md" _notices_size)
if(_notices_size LESS 1)
    message(FATAL_ERROR "Empty runtime provenance/notices status record")
endif()
string(JSON _license_status GET "${payload}" license_status)
if(_license_status STREQUAL "unresolved")
    message(STATUS "Runtime license provenance unresolved: local development only; release review remains required")
endif()
string(JSON major GET "${payload}" schema_version)
if(NOT major EQUAL 1)
    message(FATAL_ERROR "Unsupported runtime manifest major ${major}")
endif()
string(JSON count LENGTH "${payload}" components)
if(NOT count EQUAL 2)
    message(FATAL_ERROR "Both runtime components are required")
endif()
set(seen "")
foreach(index RANGE 0 1)
    string(JSON component GET "${payload}" components ${index})
    string(JSON id GET "${component}" component)
    if(id IN_LIST seen)
        message(FATAL_ERROR "Duplicate component ${id}")
    endif()
    list(APPEND seen "${id}")
    if(id STREQUAL "colmap")
        set(root "${COLMAP_ROOT}")
        set(expected_entry "bin/sfm.exe")
    elseif(id STREQUAL "super_resolution")
        set(root "${SUPERRES_ROOT}")
        set(expected_entry "preprocess.exe")
    else()
        message(FATAL_ERROR "Unknown runtime ${id}")
    endif()
    string(JSON entry GET "${component}" entrypoint)
    if(NOT entry STREQUAL expected_entry)
        message(FATAL_ERROR "Unexpected entrypoint ${entry}")
    endif()
    string(JSON files LENGTH "${component}" files)
    if(files LESS 1)
        message(FATAL_ERROR "Empty runtime manifest")
    endif()
    math(EXPR last "${files} - 1")
    set(expected "")
    foreach(file_index RANGE 0 ${last})
        string(JSON relative GET "${component}" files ${file_index} path)
        string(JSON hash GET "${component}" files ${file_index} sha256)
        string(JSON bytes GET "${component}" files ${file_index} byte_size)
        if(IS_ABSOLUTE "${relative}" OR relative MATCHES "(^|[/\\\\])\\.\\.([/\\\\]|$)" OR relative MATCHES ":")
            message(FATAL_ERROR "Unsafe runtime path ${relative}")
        endif()
        if(relative IN_LIST expected)
            message(FATAL_ERROR "Duplicate runtime path ${relative}")
        endif()
        list(APPEND expected "${relative}")
        if(NOT EXISTS "${root}/${relative}" OR IS_SYMLINK "${root}/${relative}")
            message(FATAL_ERROR "Missing or linked runtime file ${root}/${relative}")
        endif()
        file(SIZE "${root}/${relative}" actual_size)
        file(SHA256 "${root}/${relative}" actual_hash)
        if(NOT actual_size EQUAL bytes OR NOT actual_hash STREQUAL hash)
            message(FATAL_ERROR "Runtime hash/size mismatch: ${root}/${relative}")
        endif()
    endforeach()
    if(NOT entry IN_LIST expected)
        message(FATAL_ERROR "Entrypoint missing from manifest")
    endif()
    file(GLOB_RECURSE actual LIST_DIRECTORIES FALSE RELATIVE "${root}" "${root}/*")
    list(SORT actual)
    list(SORT expected)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Runtime file set does not match manifest: ${root}")
    endif()
endforeach()
message(STATUS "Verified COLMAP/SR runtime hashes")
cmake_policy(POP)
